materiales:
  Piedra: 300.0
  Madera: 20.0
  Item_Mobs: 35.0
  Tierra: 10.0
  Arena: 15.0
  Hierro: 150.0
  Oro: 250.0
  Diamante: 500.0
  Netherite: 1000.0

biomas:
  nevado: 80.0
  desierto: 50.0
  mar: 100.0
  sabana: 120.0
  jungla: 180.0
  cueva: 90.0

rareza:
  comun: 0.0
  raro: 400.0
  legendario: 1000.0

dimensiones:
  nether: 500.0
  end: 3000.0
  overworld: 10.0

categorias:
  Building_Blocks: 150.0
  Colored_Blocks: 70.0
  Natural_Blocks: 20.0
  Functional_Blocks: 130.0
  Redstone_Blocks: 300.0
  Tools_&_Utilities: 390.0
  Combat: 900.0
  Food_&_Drinks: 200.0
  Ingredients: 290.0
  Spawn_Eggs: 1000000.0

descuentos_grupos:
  default: 5.0
  vip: 20.0
  vip+: 40.0
  vip++: 70.0

trabajos:
  Granjero: 10
  Minero: 10
  Herrero: 10
  Carpintero: 10
  Agricultor: 10
  Alquimista: 10
  Guardia: 10
  Cazador: 10

grupos_desbloqueos:
  vip+: 'raro'
  vip++: 'raro, legendario'