materiales:
  Piedra: 8.0
  Madera: 5.0
  Item_Mobs: 10.5
  Tierra: 3.9
  Arena: 7.2
  Hierro: 22.0
  Oro: 50.0
  Diamante: 44.0
  Netherite: 970.3

biomas:
  nevado: 80.0
  desierto: 50.0
  mar: 120.0
  sabana: 80.0
  jungla: 80.0
  cueva: 100.0

rareza:
  comun: 8.0
  raro: 3370.0
  legendario: 18799.5

dimensiones:
  nether: 799.0
  end: 3000.0
  overworld: 10.0

categorias:
  Building_Blocks: 15.0
  Colored_Blocks: 15.0
  Natural_Blocks: 7.0
  Functional_Blocks: 62.0
  Redstone_Blocks: 33.0
  Tools_&_Utilities: 561.0
  Combat: 178.0
  Food_&_Drinks: 30.0
  Ingredients: 69.0
  Spawn_Eggs: 1000000.0

descuentos_grupos:
  default: 1.0
  piedra: 8.0
  platino: 20.0
  diamante: 40.0
  esmeralda: 70.0
  netherita: 90.0

trabajos:
  Granjero: 10
  Minero: 10
  Herrero: 10
  Carpintero: 10
  Agricultor: 10
  Alquimista: 10
  Guardia: 10
  Cazador: 10

grupos_desbloqueos:
  piedra: 'comun'
  platino: 'comun, raro'
  diamante: 'comun, raro, legendario'
  esmeralda: 'comun, raro, legendario'
  netherita: 'comun, raro, legendario'