name: MenuInteractivo
version: '1.0.0.27-SNAPSHOT'
main: AndromeDraick.menuInteractivo.MenuInteractivo
api-version: '1.21.1'
softdepend: [Vault]
folia-supported: true



commands:
  menu:
    description: Abre el menú interactivo
    usage: /menu

  tmi:
    description: Sistema de tienda personalizada
    usage: /tmi <comprar|vender> <item> <cantidad>
    aliases: [tienda, shop]
    permission: menuinteractivo.usar
    permission-message: No tienes permiso para usar la tienda.
    tab-completer: AndromeDraick.menuInteractivo.comandos.Comandos

  rnmi:
    description: Comandos de reinos
    usage: /rnmi <crear|unir|salir|eliminar|listar|info> [args]
    permission: menuinteractivo.reino.comandos
    permission-message: No tienes permiso para gestionar reinos.
  bmi:
    description: Comandos de bancos
    usage: /bmi <crear|pendientes|aprobar|rechazar|listar|unir|salir|saldo|depositar|retirar|banco|ayuda> [args]
    permission: menuinteractivo.banco
    permission-message: No tienes permiso para gestionar bancos.
permissions:
  menuinteractivo.usar:
    description: Permite usar el sistema de tienda personalizada.
    default: true

  menuinteractivo.reino.comandos:
    description: Permite gestionar reinos.
    default: true

  menuinteractivo.reino.comandos.crear:
    description: Permite crear nuevos reinos
    default: op

  menuinteractivo.banco:
    description: Permite crear y gestionar bancos.
    default: op