name: MenuInteractivo
version: '1.0.0.10-SNAPSHOT'
main: AndromeDraick.menuInteractivo.MenuInteractivo
api-version: '1.21'
folia-supported: true
commands:
  menu:
    description: Abre el menú interactivo
    usage: /menu
  tmi:
    usage: /tmi <comprar|vender> <item> <cantidad>
    description: Sistema de tienda personalizada
    aliases: [ tienda, shop ]
    permission: menuinteractivo.usar
    permission-message: No tienes permiso.
    tab-completer: AndromeDraick.menuInteractivo.comandos.Comandos