items_custom:
  STONE:
    material: Piedra
    bioma: cueva
    rareza: comun
    dimension: overworld
    categoria: Building_Blocks
    trabajo: Minero

  OAK_LOG:
    material: Madera
    bioma: sabana
    rareza: comun
    dimension: overworld
    categoria: Building_Blocks
    trabajo: Carpintero, Cazador

  gunpowder:
    material: Item_Mobs
    bioma: sabana
    rareza: comun
    dimension: overworld
    categoria: Building_Blocks
    trabajo: Cazador

  cooked_salmon:
    material: Madera
    bioma: sabana
    rareza: comun
    dimension: overworld
    categoria: Building_Blocks
    trabajo: Cazador

  DIAMOND_SWORD:
    material: Diamante
    bioma: cueva
    rareza: raro
    dimension: overworld
    categoria: Combat
    trabajo: Guardia, Cazador

  NETHERITE_SWORD:
    material: Netherite
    bioma: nether
    rareza: legendario
    dimension: nether
    categoria: Combat
    trabajo: Guardia

  ENDER_PEARL:
    material: Item_Mobs
    bioma: end
    rareza: raro
    dimension: end
    categoria: Ingredients
    trabajo: Cazador

  SPAWNER:
    material: Item_Mobs
    bioma: cueva
    rareza: legendario
    dimension: overworld
    categoria: Spawn_Eggs
    trabajo: Cazador
